version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: escola-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: escola
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - escola_escola-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: escola-app
    depends_on:
      - db
    volumes:
      - ./src:/app
      - ./queries:/app/queries
    networks:
      - escola_escola-net
    working_dir: /app
    command: ["python", "consulta.py"]

networks:
  escola_escola-net: